version: "3"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres:12
    env_file:
      - .env
    environment:
      POSTGRES_DB: rest_app
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "${APP_PORT}:8000"
    env_file:
      - .env
    environment:
      - directory=/app
    depends_on:
      - postgres
volumes:
  postgres-data:
